name = "TensorInference"
uuid = "c2297e78-99bd-40ad-871d-f50e56b81012"
authors = ["Jin-Guo Liu", "Martin Roa Villescas"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TropicalGEMM = "a4ad3063-64a7-4bad-8738-34ed09bc0236"
TropicalNumbers = "b3a74e9c-7526-4576-a4eb-79c0d4c32334"

[compat]
CUDA = "4"
DocStringExtensions = "0.8.6, 0.9"
OMEinsum = "0.7"
Requires = "1"
TropicalGEMM = "0.1"
TropicalNumbers = "0.5.4"
julia = "1.3"
