[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
LuxorGraphPlot = "1f49bdf2-22a7-4bc4-978b-948dc219fbbc"
ProblemReductions = "899c297d-f7d2-4ebf-8815-a35996def416"
TensorInference = "c2297e78-99bd-40ad-871d-f50e56b81012"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
